---

version: "3.3"

networks:
    tenants:
        driver: bridge

services:
    postgres:
        image: postgres:9.4
        volumes:
            - ./db-data:/var/lib/postgresql/data

    migrations:
        image: tapis/tenants-api-migrations
        volumes:
            - ./config.json:/home/tapis/config.json

    tenants:
        image: tapis/tenants-api
        ports:
            - "5000:5000"
        volumes:
            - ./config.json:/home/tapis/config.json
            - ./service.log:/home/tapis/service.log
        depends_on:
            - postgres

