"""empty message

Revision ID: a548f054abd5
Revises: 
Create Date: 2019-08-26 21:36:11.501435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a548f054abd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ldap_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=2000), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('user_dn', sa.String(length=200), nullable=False),
    sa.Column('bind_dn', sa.String(length=200), nullable=False),
    sa.Column('bind_credential', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.Enum('user', 'service', name='ldapaccounttypes'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenantOwners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('institution', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('institution'),
    sa.UniqueConstraint('username')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=2000), nullable=False),
    sa.Column('token_service', sa.String(length=2000), nullable=False),
    sa.Column('security_kernel', sa.String(length=2000), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('service_ldap_connection_id', sa.Integer(), nullable=False),
    sa.Column('user_ldap_connection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['tenantOwners.id'], ),
    sa.ForeignKeyConstraint(['service_ldap_connection_id'], ['ldap_connections.id'], ),
    sa.ForeignKeyConstraint(['user_ldap_connection_id'], ['ldap_connections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_url'),
    sa.UniqueConstraint('security_kernel'),
    sa.UniqueConstraint('tenant_id'),
    sa.UniqueConstraint('token_service')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    op.drop_table('tenantOwners')
    op.drop_table('ldap_connections')
    # ### end Alembic commands ###
